### ISSUE TITLE
[Code cleanup] Reduce code health issue reported in Codacy: Tracking bug

### ISSUE THREAD

**Issue by mebjas** [mebjas/html5-qrcode#225]
Several code health issues reported in Codacy - https://app.codacy.com/gh/mebjas/html5-qrcode/dashboard?branch=master

Goal is to reduce the issues:
 - [ ] 0 Error prone issues
 - [ ] 0 Security Issues
 - [ ] Less code style issues

**Comment by mebjas** [comment]
All error prone and security issues fixed. Several code style related issues pending.

Improve the code health over time until we get `code quality - A` score.

 - [ ] [P2] Get code quality A score
     - [ ] Add a badge to read me

**Comment by mebjas** [comment]
Removing `P1` label as all security and error prone issues have been addressed

**Comment by mebjas** [comment]
Update code health is now down to:

```
Code Style 97
Security 0
Error Prone 0
Performance 0
Compatibility 0
Unused Code 0
```

**Comment by mebjas** [comment]
Update code health is now down to:

```
Code Style 62
Security 0
Error Prone 0
Performance 0
Compatibility 0
Unused Code 0
```

**Grade: B**

**Comment by mebjas** [comment]
Update code health is now down to:

```
Code Style 34
Security 0
Error Prone 0
Performance 0
Compatibility 0
Unused Code 0
```

**Grade: A**

**Comment by mebjas** [comment]
Majority of the pending issues reported are of type:

```text
Method '{METHOD_NAME}' has a complexity of {COMPLEXITY}. Maximum allowed is {MAX_COMPLEXITY}.
```

 - [ ] Reduce method complexities, currently [16 issues](https://app.codacy.com/gh/mebjas/html5-qrcode/issues?bid=20927548&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE1NjYiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==)

**Comment by mebjas** [comment]
Update code health is now down to:

```
Code Style 20
Security 0
Error Prone 0
Performance 0
Compatibility 0
Unused Code 0
```

**Grade: A**
